baseurl = "https://digitalproductivity.coach/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "James Stuber"
title = "The Digital Productivity Coach"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Digital Productivity Coach"
copyright = "Copyright © 2019 James Stuber"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
align_left = false
lang = "en"
github = ""
email = "james@jamesstuber.com"
linkedin = ""
twitter = "uberstuber"
social_banner = "img/banner.png"
posts_navigation = true
small_banner_logo = false